name: Run Python Script with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Update conda 
      run: conda update -n base -c defaults conda --yes
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "py38_4.8.3"
        activate-environment: myenv
        environment-file: tareas/Cordero_Jp/myenv.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Install dependencies
      run: |
        conda env update --file tareas/Cordero_Jp/myenv.yml --name base
    
    - name: Run script
      run: python -c "import pandas; print(pandas.__version__)"