name: Run Python Script with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        environment-file: tareas/Cordero_Jp/myenv.yml
        python-version: 3.11
        auto-activate-base: false
        
    - name: Activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
    
    - name: Run script
      run: python -c "import polars; print(polars.__version__)"