name: Run Python Script with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        environment-file: tareas/Cordero_Jp/myenv.yml
        python-version: 3.11
        auto-activate-base: false
        
    - name: Check Conda installation
      run: |
        conda info
        conda env list